name: Wide Eyed Entertainment
favicon: null
layout_spectrum: 0.5691067029256374
typography_spectrum: 0.1561410021968186
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.0843449654057622
  lightness: 0.10296717565506697
  saturation: 0.526871838606894
  rhythmicContrast: 0.5375202579889446
purpose: []
